<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2459f2bd23d424d89abbaaa71c59f2f8
{
    public static $files = array (
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
        'f598d06aa772fa33d905e87be6398fb1' => __DIR__ . '/..' . '/symfony/polyfill-intl-idn/bootstrap.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Intl\\Normalizer\\' => 33,
            'Symfony\\Polyfill\\Intl\\Idn\\' => 26,
            'Symfony\\Contracts\\Service\\' => 26,
            'Symfony\\Contracts\\HttpClient\\' => 29,
            'Symfony\\Contracts\\EventDispatcher\\' => 34,
            'Symfony\\Component\\Mime\\' => 23,
            'Symfony\\Component\\Mailer\\Bridge\\Sendinblue\\' => 43,
            'Symfony\\Component\\Mailer\\Bridge\\Sendgrid\\' => 41,
            'Symfony\\Component\\Mailer\\Bridge\\Postmark\\' => 41,
            'Symfony\\Component\\Mailer\\Bridge\\Mailjet\\' => 40,
            'Symfony\\Component\\Mailer\\Bridge\\Mailgun\\' => 40,
            'Symfony\\Component\\Mailer\\Bridge\\Mailchimp\\' => 42,
            'Symfony\\Component\\Mailer\\Bridge\\MailPace\\' => 41,
            'Symfony\\Component\\Mailer\\Bridge\\Google\\' => 39,
            'Symfony\\Component\\Mailer\\Bridge\\Amazon\\' => 39,
            'Symfony\\Component\\Mailer\\' => 25,
            'Symfony\\Component\\HttpClient\\' => 29,
            'Symfony\\Component\\EventDispatcher\\' => 34,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\EventDispatcher\\' => 20,
            'Psr\\Container\\' => 14,
            'Psr\\Cache\\' => 10,
        ),
        'E' => 
        array (
            'Egulias\\EmailValidator\\' => 23,
        ),
        'D' => 
        array (
            'Doctrine\\Deprecations\\' => 22,
            'Doctrine\\Common\\Lexer\\' => 22,
        ),
        'A' => 
        array (
            'AsyncAws\\Ses\\' => 13,
            'AsyncAws\\Core\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-idn',
        ),
        'Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Symfony\\Contracts\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client-contracts',
        ),
        'Symfony\\Contracts\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher-contracts',
        ),
        'Symfony\\Component\\Mime\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mime',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Sendinblue\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/sendinblue-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Sendgrid\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/sendgrid-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Postmark\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/postmark-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Mailjet\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mailjet-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Mailgun\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mailgun-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Mailchimp\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mailchimp-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\MailPace\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mail-pace-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Google\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/google-mailer',
        ),
        'Symfony\\Component\\Mailer\\Bridge\\Amazon\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/amazon-mailer',
        ),
        'Symfony\\Component\\Mailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mailer',
        ),
        'Symfony\\Component\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/event-dispatcher/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Egulias\\EmailValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/egulias/email-validator/src',
        ),
        'Doctrine\\Deprecations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/deprecations/lib/Doctrine/Deprecations',
        ),
        'Doctrine\\Common\\Lexer\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/lexer/src',
        ),
        'AsyncAws\\Ses\\' => 
        array (
            0 => __DIR__ . '/..' . '/async-aws/ses/src',
        ),
        'AsyncAws\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/async-aws/core/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2459f2bd23d424d89abbaaa71c59f2f8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2459f2bd23d424d89abbaaa71c59f2f8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2459f2bd23d424d89abbaaa71c59f2f8::$classMap;

        }, null, ClassLoader::class);
    }
}
